[pytest]

; Testing scripts path
testpaths = tests
python_files = test_*.py
python_functions = test_*

; report
generate_report_on_test = True

; command line
addopts = -v -s --browser chromium --reruns 0 --reruns-delay 2 --html=reports/report.html --alluredir=reports/allure-results --clean-alluredir




; allure serve reports/allure-results 
; allure generate .\reports\allure-results\ -o .\reports\allure-report --clean
; allure open reports/allure-report