[pytest]

; Testing scripts path
testpaths = tests
python_files = test_*.py
python_functions = test_*

; Mark list
markers =
    smoke: Smoke testing
    regression: Regression testing
    slow: E2e
    login: Login testing

; report
generate_report_on_test = True

; command line
addopts = -v -s --browser chromium --reruns 1 --reruns-delay 2 --html=reports/report.html --alluredir=reports/allure-results --clean-alluredir 

; -B avoid to gen __pycache__
; -v show the console
; -s detail messages
; -n threading 