[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
generate_report_on_test = True
addopts = -v -s --capture=no --browser-channel chrome --html=reports/report.html --alluredir=reports/allure-results --clean-alluredir



; python -m pytest ./tests/test_login_by_account.py
; python -m pytest 

; --browser chromium --browser firefox --browser webkit 
; --browser chromium --browser-channel msedge
; --headed
; --slowmo 500 (ms)
; -s
; allure serve reports/allure-results 
; allure generate .\reports\allure-results\ -o .\reports\allure-report --clean
; allure open reports/allure-report